# Generated by Django 4.0.4 on 2022-05-03 20:31

from Eclipse.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_users_chats_massages_users_delete_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_users',
            new_name='Chats_users',
        ),
    ]
