# Generated by Django 4.0.4 on 2022-05-04 09:07

from Eclipse.db import migrations, models
import Eclipse.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chat_users_chats_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats_users',
            name='chat_id',
            field=models.ForeignKey(on_delete=Eclipse.db.models.deletion.CASCADE, to='chat.chats'),
        ),
        migrations.AlterField(
            model_name='chats_users',
            name='user_id',
            field=models.ForeignKey(on_delete=Eclipse.db.models.deletion.CASCADE, to='chat.users'),
        ),
        migrations.AlterField(
            model_name='massages',
            name='chat_id',
            field=models.ForeignKey(on_delete=Eclipse.db.models.deletion.CASCADE, to='chat.chats'),
        ),
        migrations.AlterField(
            model_name='massages',
            name='user_id',
            field=models.ForeignKey(on_delete=Eclipse.db.models.deletion.CASCADE, to='chat.users'),
        ),
    ]
