# Generated by Django 4.0.4 on 2022-05-04 09:53

from Eclipse.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chats_users_chat_id_alter_chats_users_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='icon',
            field=models.ImageField(upload_to='chat/img/chats'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='status',
            field=models.CharField(choices=[('pub', 'public'), ('sec', 'private')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chats_users',
            name='user_status',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.ImageField(upload_to='chat/img/users'),
        ),
    ]
