# Generated by Django 4.0.4 on 2022-05-11 11:47

import Eclipse.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eclipse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', Eclipse.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
