# Generated by Django 4.0.4 on 2022-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eclipse', '0002_alter_users_managers_chats_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
