# Generated by Django 4.0.4 on 2022-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eclipse', '0005_users_icons_alter_chats_options_alter_chats_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'verbose_name': 'Chats', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='chats_users',
            options={'verbose_name': 'Chats_users'},
        ),
        migrations.AlterModelOptions(
            name='users_icons',
            options={'verbose_name': 'User_icon', 'verbose_name_plural': 'User_icons'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='icon',
            field=models.ImageField(default='chat/icon/chat/default.jpg', upload_to='chat/icon/chat/'),
        ),
        migrations.AlterField(
            model_name='users_icons',
            name='icon',
            field=models.ImageField(default='chat/icon/users/default.jpg', upload_to='chat/icon/users'),
        ),
    ]
