# Generated by Django 4.0.4 on 2022-05-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eclipse', '0006_alter_chats_options_alter_chats_users_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eclipse.chats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chats_users',
            options={'verbose_name': 'Chats user'},
        ),
        migrations.AlterModelOptions(
            name='users_icons',
            options={'verbose_name': 'User icon', 'verbose_name_plural': 'Users icons'},
        ),
        migrations.DeleteModel(
            name='Massages',
        ),
    ]
